{"name": "test_login_with_invalid_credentials", "status": "passed", "steps": [{"name": "Logging in with invalid credentials", "status": "passed", "steps": [{"name": "Logging response", "status": "passed", "attachments": [{"name": "Response Text", "source": "aa5a4f68-90a9-4aaf-98fe-1b6ec96a3505-attachment.json", "type": "application/json"}, {"name": "Response Headers", "source": "c1f9e2de-3b2d-4bb3-a091-fc853c2a8624-attachment.json", "type": "application/json"}], "start": 1719518486431, "stop": 1719518486432}], "start": 1719518485274, "stop": 1719518486432}], "start": 1719518485274, "stop": 1719518486432, "uuid": "4060e24b-db51-470b-a32d-37b53a4021ac", "historyId": "7071ba7437dcd01d6bcb4f3d93e3edfc", "testCaseId": "7071ba7437dcd01d6bcb4f3d93e3edfc", "fullName": "tests.test_user_operations#test_login_with_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_operations"}, {"name": "host", "value": "sanya"}, {"name": "thread", "value": "4544-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_operations"}]}