{"name": "test_get_nonexistent_user", "status": "failed", "statusDetails": {"message": "AssertionError: {\"code\":1,\"type\":\"error\",\"message\":\"User not found\"}\nassert 'User not found' == 'Пользователь не найден'\n  \n  - Пользователь не найден\n  + User not found", "trace": "self = <tests.test_user_operations.TestUserOperations object at 0x0000014B51FAE390>\nuser_page = <pages.user_page.UserPage object at 0x0000014B51FD4290>\n\n    def test_get_nonexistent_user(self, user_page):\n        with allure.step(\"Получение несуществующего пользователя\"):\n            response = user_page.get_user(\"Ryan Gosling\")\n            assert response.status_code == 404, response.text\n    \n            with allure.step(\"Прикрепление данных после теста\"):\n                allure.attach(response.text, name=\"Текст овтета\", attachment_type=allure.attachment_type.JSON)\n                allure.attach(str(response.headers), name=\"Заголовки\", attachment_type=allure.attachment_type.JSON)\n    \n            if response.headers.get('Content-Type') == 'application/json':\n>               assert response.json()['message'] == \"Пользователь не найден\", response.text\nE               AssertionError: {\"code\":1,\"type\":\"error\",\"message\":\"User not found\"}\nE               assert 'User not found' == 'Пользователь не найден'\nE                 \nE                 - Пользователь не найден\nE                 + User not found\n\ntest_user_operations.py:83: AssertionError"}, "steps": [{"name": "Получение несуществующего пользователя", "status": "failed", "statusDetails": {"message": "AssertionError: {\"code\":1,\"type\":\"error\",\"message\":\"User not found\"}\nassert 'User not found' == 'Пользователь не найден'\n  \n  - Пользователь не найден\n  + User not found\n", "trace": "  File \"C:\\Users\\bbuld\\PycharmProjects\\PetShop\\tests\\test_user_operations.py\", line 83, in test_get_nonexistent_user\n    assert response.json()['message'] == \"Пользователь не найден\", response.text\n"}, "steps": [{"name": "Прикрепление данных после теста", "status": "passed", "attachments": [{"name": "Текст овтета", "source": "1b3c5685-1232-4198-98bd-e32f6f7e2278-attachment.json", "type": "application/json"}, {"name": "Заголовки", "source": "babecd86-9e8d-4363-bf1f-55e5d230d786-attachment.json", "type": "application/json"}], "start": 1719730100587, "stop": 1719730100588}], "start": 1719730099460, "stop": 1719730100588}], "start": 1719730099460, "stop": 1719730100589, "uuid": "61c1ad9c-1333-4e04-b278-a158998a624b", "historyId": "920462bc36800d833457c42b1bd38699", "testCaseId": "920462bc36800d833457c42b1bd38699", "fullName": "tests.test_user_operations.TestUserOperations#test_get_nonexistent_user", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('user_page', 'user_data', 'created_user')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_operations"}, {"name": "subSuite", "value": "TestUserOperations"}, {"name": "host", "value": "sanya"}, {"name": "thread", "value": "7868-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_operations"}]}