{"name": "test_login_with_invalid_credentials", "status": "passed", "steps": [{"name": "Вход в систему с недействительными учетными данными", "status": "passed", "steps": [{"name": "Регистрация ответа", "status": "passed", "attachments": [{"name": "Текст ответа", "source": "b6c6d858-db81-486e-891c-5bb84df22452-attachment.json", "type": "application/json"}, {"name": "Заголовки", "source": "d37a314f-99a5-450d-adae-1070a6a2bd2d-attachment.json", "type": "application/json"}], "start": 1719730743702, "stop": 1719730743703}], "start": 1719730742627, "stop": 1719730743703}], "start": 1719730742627, "stop": 1719730743703, "uuid": "732b8074-c6c9-483d-8f61-f6a9739d3935", "historyId": "15d5d744ddd2cc4bbf96e98f1487c81f", "testCaseId": "15d5d744ddd2cc4bbf96e98f1487c81f", "fullName": "tests.test_user_operations.TestUserOperations#test_login_with_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('user_page', 'user_data', 'created_user')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_operations"}, {"name": "subSuite", "value": "TestUserOperations"}, {"name": "host", "value": "sanya"}, {"name": "thread", "value": "16708-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_operations"}]}