{"name": "test_login_with_wrong_data", "status": "failed", "statusDetails": {"message": "AssertionError: Expected status code 400, but got 200. Response: {\"code\":200,\"type\":\"unknown\",\"message\":\"logged in user session:1719744298387\"}\nassert 200 == 400\n +  where 200 = <Response [200]>.status_code", "trace": "self = <tests.test_user_operations.TestUserOperations object at 0x0000025E391071D0>\nuser_page = <pages.user_page.UserPage object at 0x0000025E391B49B0>\ncreated_user = <config.data.user_data object at 0x0000025E391B4B00>\n\n    def test_login_with_wrong_data(self, user_page, created_user):\n        with allure.step(\"Вход в систему с недействительными учетными данными\"):\n            print(\"Вход в систему с недействительными учетными данными...\")\n            print(f\"Username: {created_user.username}\")\n            print(f\"Пароль: wrongpassword\")\n    \n            response = user_page.login_user(created_user.username, \"wrongpassword\")\n    \n            print(f\"HTTP статус код ответа: {response.status_code}\")\n            print(f\"Тело ответа: {response.text}\")\n    \n            with allure.step(\"Регистрация ответа\"):\n                allure.attach(response.text, name=\"Текст ответа\", attachment_type=allure.attachment_type.JSON)\n                allure.attach(str(response.headers), name=\"Заголовки\", attachment_type=allure.attachment_type.JSON)\n    \n            # Сравниваем фактический статус код с ожидаемым\n>           assert response.status_code == 400, f\"Expected status code 400, but got {response.status_code}. Response: {response.text}\"\nE           AssertionError: Expected status code 400, but got 200. Response: {\"code\":200,\"type\":\"unknown\",\"message\":\"logged in user session:1719744298387\"}\nE           assert 200 == 400\nE            +  where 200 = <Response [200]>.status_code\n\ntest_user_operations.py:187: AssertionError"}, "steps": [{"name": "Вход в систему с недействительными учетными данными", "status": "failed", "statusDetails": {"message": "AssertionError: Expected status code 400, but got 200. Response: {\"code\":200,\"type\":\"unknown\",\"message\":\"logged in user session:1719744298387\"}\nassert 200 == 400\n +  where 200 = <Response [200]>.status_code\n", "trace": "  File \"C:\\Users\\bbuld\\PycharmProjects\\PetShop\\tests\\test_user_operations.py\", line 187, in test_login_with_wrong_data\n    assert response.status_code == 400, f\"Expected status code 400, but got {response.status_code}. Response: {response.text}\"\n"}, "steps": [{"name": "Регистрация ответа", "status": "passed", "attachments": [{"name": "Текст ответа", "source": "3e3bc9d2-39fd-43b6-9504-ab1b6afc549a-attachment.json", "type": "application/json"}, {"name": "Заголовки", "source": "9cc939ea-9934-49bb-baeb-8e0375303791-attachment.json", "type": "application/json"}], "start": 1719744299422, "stop": 1719744299423}], "start": 1719744298303, "stop": 1719744299423}], "attachments": [{"name": "stdout", "source": "aa097c58-2a06-477b-b775-678712c855b0-attachment.txt", "type": "text/plain"}], "start": 1719744298302, "stop": 1719744299423, "uuid": "d61aa855-3f4e-469a-ab76-88f9367e9ff8", "historyId": "0d8e9726cf1abe3c1559839cfa6c0c2e", "testCaseId": "0d8e9726cf1abe3c1559839cfa6c0c2e", "fullName": "tests.test_user_operations.TestUserOperations#test_login_with_wrong_data", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('user_page', 'user_data', 'created_user')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_operations"}, {"name": "subSuite", "value": "TestUserOperations"}, {"name": "host", "value": "sanya"}, {"name": "thread", "value": "10904-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_operations"}]}