{"name": "test_update_user", "status": "broken", "statusDetails": {"message": "AttributeError: 'str' object has no attribute 'id'", "trace": "@pytest.fixture(scope=\"module\")\n    def user_data():\n>       return generate_user_data()\n\n..\\conftest.py:11: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    def generate_user_data():\n        user = \"user1\"\n>       user.id = generate_id()\nE       AttributeError: 'str' object has no attribute 'id'\n\n..\\config\\generator.py:34: AttributeError"}, "start": 1719729919458, "stop": 1719729919458, "uuid": "e3fc8ca3-c3e6-400e-9e3f-4fed9212fb36", "historyId": "633f41953d1a63e4aafc1362892a6297", "testCaseId": "633f41953d1a63e4aafc1362892a6297", "fullName": "tests.test_user_operations.TestUserOperations#test_update_user", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('user_page', 'user_data', 'created_user')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_operations"}, {"name": "subSuite", "value": "TestUserOperations"}, {"name": "host", "value": "sanya"}, {"name": "thread", "value": "7900-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_operations"}]}