{"name": "test_login_with_invalid_credentials", "status": "passed", "steps": [{"name": "Вход в систему с недействительными учетными данными", "status": "passed", "steps": [{"name": "Регистрация ответа", "status": "passed", "attachments": [{"name": "Текст ответа", "source": "221f9367-4fac-49ef-acbe-55f8395a0c3e-attachment.json", "type": "application/json"}, {"name": "Заголовки", "source": "da9c570a-d70e-4c92-ad53-68d3b57935fa-attachment.json", "type": "application/json"}], "start": 1719732838814, "stop": 1719732838815}], "start": 1719732837763, "stop": 1719732838815}], "start": 1719732837763, "stop": 1719732838816, "uuid": "6567e2f4-63a1-4a3e-b6f9-393659df020f", "historyId": "15d5d744ddd2cc4bbf96e98f1487c81f", "testCaseId": "15d5d744ddd2cc4bbf96e98f1487c81f", "fullName": "tests.test_user_operations.TestUserOperations#test_login_with_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('user_page', 'user_data', 'created_user')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_operations"}, {"name": "subSuite", "value": "TestUserOperations"}, {"name": "host", "value": "sanya"}, {"name": "thread", "value": "16372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_operations"}]}