{"name": "test_update_user", "status": "broken", "statusDetails": {"message": "TypeError: User() takes no arguments", "trace": "cls = <class 'tests.test_user_operations.TestUserAPI'>\n\n    @classmethod\n    def setup_class(cls):\n        cls.user_page = UserPage()\n>       cls.user_data = generate_user().__dict__\n\ntest_user_operations.py:30: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\n    def generate_user():\n>       return User(\n            id=random.randint(1, 100),\n            username=fake.user_name(),\n            firstName=fake.first_name(),\n            lastName=fake.last_name(),\n            email=fake.safe_email(),\n            password=fake.password(),\n            phone=\"+7922964\" + ''.join(random.choices(string.digits, k=4)),\n            userStatus=random.randint(0, 100)\n        )\nE       TypeError: User() takes no arguments\n\n..\\config\\generator.py:8: TypeError"}, "start": 1719518114694, "stop": 1719518114694, "uuid": "80d5c707-472a-4485-b308-6723bc3ca0d2", "historyId": "44d24e7e7eba5ad1e6a33387bc867949", "testCaseId": "44d24e7e7eba5ad1e6a33387bc867949", "fullName": "tests.test_user_operations.TestUserAPI#test_update_user", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('user_page')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_operations"}, {"name": "subSuite", "value": "TestUserAPI"}, {"name": "host", "value": "sanya"}, {"name": "thread", "value": "18616-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_operations"}]}