{"name": "test_login_with_invalid_credentials", "status": "passed", "steps": [{"name": "Вход в систему с недействительными учетными данными", "status": "passed", "steps": [{"name": "Регистрация ответа", "status": "passed", "attachments": [{"name": "Текст ответа", "source": "da87ca52-44e3-4e4b-8a00-8613a7068d15-attachment.json", "type": "application/json"}, {"name": "Заголовки", "source": "16a4424a-e13c-4209-8b44-c79088c98d0f-attachment.json", "type": "application/json"}], "start": 1719742914326, "stop": 1719742914327}], "start": 1719742913129, "stop": 1719742914327}], "start": 1719742913129, "stop": 1719742914327, "uuid": "d1534c49-95fd-4b0b-b1e5-7927226d291c", "historyId": "15d5d744ddd2cc4bbf96e98f1487c81f", "testCaseId": "15d5d744ddd2cc4bbf96e98f1487c81f", "fullName": "tests.test_user_operations.TestUserOperations#test_login_with_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('user_page', 'user_data', 'created_user')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_operations"}, {"name": "subSuite", "value": "TestUserOperations"}, {"name": "host", "value": "sanya"}, {"name": "thread", "value": "8812-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_operations"}]}