{"name": "test_create_user", "status": "failed", "statusDetails": {"message": "Failed: JSON schema validation error: 'id' is a required property\n\nFailed validating 'required' in schema:\n    {'properties': {'email': {'type': 'string'},\n                    'firstName': {'type': 'string'},\n                    'id': {'type': 'integer'},\n                    'lastName': {'type': 'string'},\n                    'password': {'type': 'string'},\n                    'phone': {'type': 'string'},\n                    'userStatus': {'type': 'integer'},\n                    'username': {'type': 'string'}},\n     'required': ['id',\n                  'username',\n                  'firstName',\n                  'lastName',\n                  'email',\n                  'password',\n                  'phone',\n                  'userStatus'],\n     'type': 'object'}\n\nOn instance:\n    {'code': 200, 'message': '9223372036854775807', 'type': 'unknown'}", "trace": "user_page = <pages.user_page.UserPage object at 0x0000022B3C1E1340>\n\n    def test_create_user(user_page):\n        with allure.step(\"Creating a new user\"):\n            user_data = {\n                \"id\": 0,\n                \"username\": \"testuser\",\n                \"firstName\": \"Test\",\n                \"lastName\": \"User\",\n                \"email\": \"testuser@example.com\",\n                \"password\": \"password123\",\n                \"phone\": \"123456789\",\n                \"userStatus\": 0\n            }\n            response = user_page.create_user(user_data)\n            assert response.status_code == 200, response.text\n    \n            with allure.step(\"Logging response\"):\n                allure.attach(response.text, name=\"Response Text\", attachment_type=allure.attachment_type.JSON)\n                allure.attach(str(response.headers), name=\"Response Headers\", attachment_type=allure.attachment_type.JSON)\n    \n            if response.headers.get('Content-Type') == 'application/json':\n                data = response.json()\n                with allure.step(\"Validating JSON schema\"):\n                    try:\n>                       validate(instance=data, schema=user_schema)\n\ntest_user_operations.py:48: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\ninstance = {'code': 200, 'message': '9223372036854775807', 'type': 'unknown'}\nschema = {'properties': {'email': {'type': 'string'}, 'firstName': {'type': 'string'}, 'id': {'type': 'integer'}, 'lastName': {...: 'string'}, ...}, 'required': ['id', 'username', 'firstName', 'lastName', 'email', 'password', ...], 'type': 'object'}\ncls = <class 'jsonschema.validators.Draft202012Validator'>, args = ()\nkwargs = {}\nvalidator = Draft202012Validator(schema={'properties': {'email': {'type': 'string'}, 'firstName': {'type': 'string'}, 'id': {'type...quired': ['id', 'username', 'firstName', 'lastName', 'email', 'password', ...], 'type': 'object'}, format_checker=None)\nerror = <ValidationError: \"'id' is a required property\">\n\n    def validate(instance, schema, cls=None, *args, **kwargs):  # noqa: D417\n        \"\"\"\n        Validate an instance under the given schema.\n    \n            >>> validate([2, 3, 4], {\"maxItems\": 2})\n            Traceback (most recent call last):\n                ...\n            ValidationError: [2, 3, 4] is too long\n    \n        :func:`~jsonschema.validators.validate` will first verify that the\n        provided schema is itself valid, since not doing so can lead to less\n        obvious error messages and fail in less obvious or consistent ways.\n    \n        If you know you have a valid schema already, especially\n        if you intend to validate multiple instances with\n        the same schema, you likely would prefer using the\n        `jsonschema.protocols.Validator.validate` method directly on a\n        specific validator (e.g. ``Draft202012Validator.validate``).\n    \n    \n        Arguments:\n    \n            instance:\n    \n                The instance to validate\n    \n            schema:\n    \n                The schema to validate with\n    \n            cls (jsonschema.protocols.Validator):\n    \n                The class that will be used to validate the instance.\n    \n        If the ``cls`` argument is not provided, two things will happen\n        in accordance with the specification. First, if the schema has a\n        :kw:`$schema` keyword containing a known meta-schema [#]_ then the\n        proper validator will be used. The specification recommends that\n        all schemas contain :kw:`$schema` properties for this reason. If no\n        :kw:`$schema` property is found, the default validator class is the\n        latest released draft.\n    \n        Any other provided positional and keyword arguments will be passed\n        on when instantiating the ``cls``.\n    \n        Raises:\n    \n            `jsonschema.exceptions.ValidationError`:\n    \n                if the instance is invalid\n    \n            `jsonschema.exceptions.SchemaError`:\n    \n                if the schema itself is invalid\n    \n        .. rubric:: Footnotes\n        .. [#] known by a validator registered with\n            `jsonschema.validators.validates`\n    \n        \"\"\"\n        if cls is None:\n            cls = validator_for(schema)\n    \n        cls.check_schema(schema)\n        validator = cls(schema, *args, **kwargs)\n        error = exceptions.best_match(validator.iter_errors(instance))\n        if error is not None:\n>           raise error\nE           jsonschema.exceptions.ValidationError: 'id' is a required property\nE           \nE           Failed validating 'required' in schema:\nE               {'properties': {'email': {'type': 'string'},\nE                               'firstName': {'type': 'string'},\nE                               'id': {'type': 'integer'},\nE                               'lastName': {'type': 'string'},\nE                               'password': {'type': 'string'},\nE                               'phone': {'type': 'string'},\nE                               'userStatus': {'type': 'integer'},\nE                               'username': {'type': 'string'}},\nE                'required': ['id',\nE                             'username',\nE                             'firstName',\nE                             'lastName',\nE                             'email',\nE                             'password',\nE                             'phone',\nE                             'userStatus'],\nE                'type': 'object'}\nE           \nE           On instance:\nE               {'code': 200, 'message': '9223372036854775807', 'type': 'unknown'}\n\n..\\.venv\\Lib\\site-packages\\jsonschema\\validators.py:1332: ValidationError\n\nDuring handling of the above exception, another exception occurred:\n\nuser_page = <pages.user_page.UserPage object at 0x0000022B3C1E1340>\n\n    def test_create_user(user_page):\n        with allure.step(\"Creating a new user\"):\n            user_data = {\n                \"id\": 0,\n                \"username\": \"testuser\",\n                \"firstName\": \"Test\",\n                \"lastName\": \"User\",\n                \"email\": \"testuser@example.com\",\n                \"password\": \"password123\",\n                \"phone\": \"123456789\",\n                \"userStatus\": 0\n            }\n            response = user_page.create_user(user_data)\n            assert response.status_code == 200, response.text\n    \n            with allure.step(\"Logging response\"):\n                allure.attach(response.text, name=\"Response Text\", attachment_type=allure.attachment_type.JSON)\n                allure.attach(str(response.headers), name=\"Response Headers\", attachment_type=allure.attachment_type.JSON)\n    \n            if response.headers.get('Content-Type') == 'application/json':\n                data = response.json()\n                with allure.step(\"Validating JSON schema\"):\n                    try:\n                        validate(instance=data, schema=user_schema)\n                    except ValidationError as e:\n>                       pytest.fail(f\"JSON schema validation error: {e}\")\nE                       Failed: JSON schema validation error: 'id' is a required property\nE                       \nE                       Failed validating 'required' in schema:\nE                           {'properties': {'email': {'type': 'string'},\nE                                           'firstName': {'type': 'string'},\nE                                           'id': {'type': 'integer'},\nE                                           'lastName': {'type': 'string'},\nE                                           'password': {'type': 'string'},\nE                                           'phone': {'type': 'string'},\nE                                           'userStatus': {'type': 'integer'},\nE                                           'username': {'type': 'string'}},\nE                            'required': ['id',\nE                                         'username',\nE                                         'firstName',\nE                                         'lastName',\nE                                         'email',\nE                                         'password',\nE                                         'phone',\nE                                         'userStatus'],\nE                            'type': 'object'}\nE                       \nE                       On instance:\nE                           {'code': 200, 'message': '9223372036854775807', 'type': 'unknown'}\n\ntest_user_operations.py:50: Failed"}, "steps": [{"name": "Creating a new user", "status": "failed", "statusDetails": {"message": "Failed: JSON schema validation error: 'id' is a required property\n\nFailed validating 'required' in schema:\n    {'properties': {'email': {'type': 'string'},\n                    'firstName': {'type': 'string'},\n                    'id': {'type': 'integer'},\n                    'lastName': {'type': 'string'},\n                    'password': {'type': 'string'},\n                    'phone': {'type': 'string'},\n                    'userStatus': {'type': 'integer'},\n                    'username': {'type': 'string'}},\n     'required': ['id',\n                  'username',\n                  'firstName',\n                  'lastName',\n                  'email',\n                  'password',\n                  'phone',\n                  'userStatus'],\n     'type': 'object'}\n\nOn instance:\n    {'code': 200, 'message': '9223372036854775807', 'type': 'unknown'}\n", "trace": "  File \"C:\\Users\\bbuld\\PycharmProjects\\PetShop\\tests\\test_user_operations.py\", line 50, in test_create_user\n    pytest.fail(f\"JSON schema validation error: {e}\")\n  File \"C:\\Users\\bbuld\\PycharmProjects\\PetShop\\.venv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "steps": [{"name": "Logging response", "status": "passed", "attachments": [{"name": "Response Text", "source": "d86227bc-08db-4e77-8cca-56e88302d37f-attachment.json", "type": "application/json"}, {"name": "Response Headers", "source": "727e9b1e-5f6b-4426-a54f-84c28983a0e9-attachment.json", "type": "application/json"}], "start": 1719518476279, "stop": 1719518476280}, {"name": "Validating JSON schema", "status": "failed", "statusDetails": {"message": "Failed: JSON schema validation error: 'id' is a required property\n\nFailed validating 'required' in schema:\n    {'properties': {'email': {'type': 'string'},\n                    'firstName': {'type': 'string'},\n                    'id': {'type': 'integer'},\n                    'lastName': {'type': 'string'},\n                    'password': {'type': 'string'},\n                    'phone': {'type': 'string'},\n                    'userStatus': {'type': 'integer'},\n                    'username': {'type': 'string'}},\n     'required': ['id',\n                  'username',\n                  'firstName',\n                  'lastName',\n                  'email',\n                  'password',\n                  'phone',\n                  'userStatus'],\n     'type': 'object'}\n\nOn instance:\n    {'code': 200, 'message': '9223372036854775807', 'type': 'unknown'}\n", "trace": "  File \"C:\\Users\\bbuld\\PycharmProjects\\PetShop\\tests\\test_user_operations.py\", line 50, in test_create_user\n    pytest.fail(f\"JSON schema validation error: {e}\")\n  File \"C:\\Users\\bbuld\\PycharmProjects\\PetShop\\.venv\\Lib\\site-packages\\_pytest\\outcomes.py\", line 177, in fail\n    raise Failed(msg=reason, pytrace=pytrace)\n"}, "start": 1719518476280, "stop": 1719518476282}], "start": 1719518474822, "stop": 1719518476284}], "start": 1719518474822, "stop": 1719518476284, "uuid": "9a3addca-72eb-41ef-ac55-0ba4507a826f", "historyId": "6a9a92177c91df2f5905f470fa6b1462", "testCaseId": "6a9a92177c91df2f5905f470fa6b1462", "fullName": "tests.test_user_operations#test_create_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_operations"}, {"name": "host", "value": "sanya"}, {"name": "thread", "value": "4544-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_operations"}]}