{"name": "test_login_with_invalid_credentials", "status": "passed", "steps": [{"name": "Logging in with invalid credentials", "status": "passed", "steps": [{"name": "Logging response", "status": "passed", "attachments": [{"name": "Response Text", "source": "58dccc13-fd17-478c-b590-64db3951aba0-attachment.json", "type": "application/json"}, {"name": "Response Headers", "source": "2eb17c24-e94f-4b5b-9e08-f5ff8bbc996f-attachment.json", "type": "application/json"}], "start": 1719518332629, "stop": 1719518332630}], "start": 1719518331473, "stop": 1719518332630}], "start": 1719518331473, "stop": 1719518332630, "uuid": "ef71276a-651f-42c2-8b57-3f91a9953f9c", "historyId": "7071ba7437dcd01d6bcb4f3d93e3edfc", "testCaseId": "7071ba7437dcd01d6bcb4f3d93e3edfc", "fullName": "tests.test_user_operations#test_login_with_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_operations"}, {"name": "host", "value": "sanya"}, {"name": "thread", "value": "18040-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_operations"}]}