{"name": "test_login_user", "status": "broken", "statusDetails": {"message": "AttributeError: 'UserPage' object has no attribute 'get_logs'", "trace": "self = <tests.test_user_operations.TestUserOperations object at 0x000001F477BF2030>\nuser_page = <pages.user_page.UserPage object at 0x000001F477B542C0>\ncreated_user = <config.data.user_data object at 0x000001F477C58D10>\n\n    def test_login_user(self, user_page, created_user):\n        with allure.step(\"Вход в систему пользователем\"):\n            print(\"Вход в систему пользователем...\")\n            print(f\"Username: {created_user.username}\")\n            print(f\"Password: {created_user.password}\")\n            response = user_page.login_user(created_user.username, created_user.password)\n            print(f\"Тело ответа: {response.text}\")\n            assert response.status_code == 200, response.text\n            response_json = response.json()\n            expected_response = json.loads(json.dumps(expected_login_success_response))\n    \n            # Проверка \"logged in user session\" в \"message\"\n            assert response_json[\"code\"] == expected_response[\"code\"], \\\n                f\"Expected code {expected_response['code']}, but got {response_json['code']}\"\n            assert response_json[\"type\"] == expected_response[\"type\"], \\\n                f\"Expected type {expected_response['type']}, but got {response_json['type']}\"\n            assert response_json[\"message\"].startswith(expected_response[\"message\"]), \\\n                f\"Expected message to start with {expected_response['message']}, but got {response_json['message']}\"\n    \n            print(\"Вход в систему выполнен успешно\")\n    \n        with allure.step(\"Прикрепление логов\"):\n>           logs = user_page.get_logs()\nE           AttributeError: 'UserPage' object has no attribute 'get_logs'\n\ntest_user_operations.py:141: AttributeError"}, "steps": [{"name": "Вход в систему пользователем", "status": "passed", "start": 1719747676978, "stop": 1719747678167}, {"name": "Прикрепление логов", "status": "broken", "statusDetails": {"message": "AttributeError: 'UserPage' object has no attribute 'get_logs'\n", "trace": "  File \"C:\\Users\\bbuld\\PycharmProjects\\PetShop\\tests\\test_user_operations.py\", line 141, in test_login_user\n    logs = user_page.get_logs()\n           ^^^^^^^^^^^^^^^^^^\n"}, "start": 1719747678167, "stop": 1719747678167}], "attachments": [{"name": "stdout", "source": "3bf8c5c2-0b46-459c-a5d6-9b07082ba463-attachment.txt", "type": "text/plain"}], "start": 1719747676978, "stop": 1719747678168, "uuid": "4fee728c-5cd9-4715-b11b-93d7086d3b54", "historyId": "0a8dce3652b45bd61a977825b4ab5668", "testCaseId": "0a8dce3652b45bd61a977825b4ab5668", "fullName": "tests.test_user_operations.TestUserOperations#test_login_user", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('user_page', 'user_data', 'created_user')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_operations"}, {"name": "subSuite", "value": "TestUserOperations"}, {"name": "host", "value": "sanya"}, {"name": "thread", "value": "16608-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_operations"}]}