{"name": "test_login_with_invalid_credentials", "status": "passed", "steps": [{"name": "Вход в систему с недействительными учетными данными", "status": "passed", "steps": [{"name": "Регистрация ответа", "status": "passed", "attachments": [{"name": "Текст ответа", "source": "8eb9725d-6089-41c9-8d82-4c11810d7120-attachment.json", "type": "application/json"}, {"name": "Заголовки", "source": "b2b01379-74b9-419d-97bd-fe5c7c5ce031-attachment.json", "type": "application/json"}], "start": 1719739086852, "stop": 1719739086853}], "start": 1719739085761, "stop": 1719739086853}], "start": 1719739085761, "stop": 1719739086854, "uuid": "7a52aee8-5cea-41eb-8bb3-b1f824a7ebbc", "historyId": "15d5d744ddd2cc4bbf96e98f1487c81f", "testCaseId": "15d5d744ddd2cc4bbf96e98f1487c81f", "fullName": "tests.test_user_operations.TestUserOperations#test_login_with_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('user_page', 'user_data', 'created_user')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_operations"}, {"name": "subSuite", "value": "TestUserOperations"}, {"name": "host", "value": "sanya"}, {"name": "thread", "value": "4144-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_operations"}]}