{"name": "test_login_with_invalid_credentials", "status": "passed", "steps": [{"name": "Вход в систему с недействительными учетными данными", "status": "passed", "steps": [{"name": "Регистрация ответа", "status": "passed", "attachments": [{"name": "Текст ответа", "source": "19dc1bfd-dc47-4678-98a5-3de8d9874503-attachment.json", "type": "application/json"}, {"name": "Заголовки", "source": "4dc40912-d562-417a-a94c-154d38575fce-attachment.json", "type": "application/json"}], "start": 1719738165448, "stop": 1719738165449}], "start": 1719738164287, "stop": 1719738165449}], "start": 1719738164287, "stop": 1719738165449, "uuid": "a57b5b8e-d180-4b83-a4c6-285dd4033c12", "historyId": "15d5d744ddd2cc4bbf96e98f1487c81f", "testCaseId": "15d5d744ddd2cc4bbf96e98f1487c81f", "fullName": "tests.test_user_operations.TestUserOperations#test_login_with_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('user_page', 'user_data', 'created_user')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_operations"}, {"name": "subSuite", "value": "TestUserOperations"}, {"name": "host", "value": "sanya"}, {"name": "thread", "value": "4592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_operations"}]}