{"name": "test_login_with_invalid_credentials", "status": "passed", "steps": [{"name": "Вход в систему с недействительными учетными данными", "status": "passed", "steps": [{"name": "Регистрация ответа", "status": "passed", "attachments": [{"name": "Текст ответа", "source": "a6418000-1529-4f9b-9030-47ed1deb6da5-attachment.json", "type": "application/json"}, {"name": "Заголовки", "source": "1c3aaf80-f0ad-49a2-a490-cb869e122f1b-attachment.json", "type": "application/json"}], "start": 1719739559856, "stop": 1719739559857}], "start": 1719739558702, "stop": 1719739559857}], "start": 1719739558701, "stop": 1719739559858, "uuid": "12573206-4bb5-4e93-9340-e756e77a50bf", "historyId": "15d5d744ddd2cc4bbf96e98f1487c81f", "testCaseId": "15d5d744ddd2cc4bbf96e98f1487c81f", "fullName": "tests.test_user_operations.TestUserOperations#test_login_with_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('user_page', 'user_data', 'created_user')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_operations"}, {"name": "subSuite", "value": "TestUserOperations"}, {"name": "host", "value": "sanya"}, {"name": "thread", "value": "344-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_operations"}]}